[lint.rules]
"lint/security/noDangerouslySetInnerHtml" = "off"
"lint/style/useSelfClosingElements" = "off"
"lint/suspicious/noArrayIndexKey" = "off"
"lint/suspicious/noExplicitAny" = "off"
"lint/a11y/useAltText" = "off"
"lint/a11y/useButtonType" = "off" 

[linter.rules.security]
noDangerouslySetInnerHtml = "off" 

[ignore]
patterns = [
  "node_modules/**",
  ".next/**",
  "Z-EXAMPLE-WEBSITE/**",
  "test-results/**",
  "**/*.test.tsx",
  "**/*.test.ts",
  "**/*.nft.json",
] 