[lint.rules]
"lint/security/noDangerouslySetInnerHtml" = "off"
"lint/style/useSelfClosingElements" = "off"
"lint/suspicious/noArrayIndexKey" = "off"
"lint/suspicious/noExplicitAny" = "off"
"lint/a11y/useAltText" = "off"
"lint/a11y/useButtonType" = "off"
"lint/style/useImportType" = "off" 

[linter.rules.security]
noDangerouslySetInnerHtml = "off" 

# Enable VCS ignore file for consistent ignore behavior
[vcs]
enabled = true
useIgnoreFile = true
clientKind = "git"

# Global ignore patterns for build artifacts, dependencies, examples, test output, and vendor scripts
[files]
ignore = [
  "node_modules/**",
  "Z-EXAMPLE-WEBSITE/**",
  "test-results/**",
  "public/~partytown/**",
  "docs/archived/**",
  "docs/building/inspiration/**"
]
ignoreUnknown = true

# Formatter should skip these paths too
[formatter]
ignore = [
  "node_modules/**",
  "Z-EXAMPLE-WEBSITE/**",
  "test-results/**",
  "docs/archived/**",
  "public/~partytown/**",
  "docs/building/inspiration/**"
]

# Linter should skip these paths too
[linter]
ignore = [
  "node_modules/**",
  "Z-EXAMPLE-WEBSITE/**",
  "test-results/**",
  "public/~partytown/**",
  "docs/building/inspiration/**",
  "docs/archived/**"
]

# organizeImports should skip these paths too
[organizeImports]
ignore = [
  "node_modules/**",
  "Z-EXAMPLE-WEBSITE/**",
  "docs/archived/**",
  "test-results/**",
  "public/~partytown/**"
]

# Disable Biome for build artifacts and vendor code
[[overrides]]
include = ["**/.next/**", "public/~partytown/**"]

[overrides.formatter]
enabled = false

[overrides.linter]
enabled = false

[overrides.organizeImports]
enabled = false 