/**
 * Copy this file to site.config.local.ts and fill in the values.
 * All default settings live here for merging with your local overrides.
 */

export const siteConfig = {
	site: {
		title: "",
		description: "",
		url: "",
		name: "",
		openGraph: { image: { url: "", width: 1200, height: 630, alt: "" } },
		twitterImage: "",
	},
	theme: {
		colors: { primary: "#1E3A8A", secondary: "#60A5FA", accent: "#3B82F6" },
		logo: { src: "", alt: "" },
		favicon: "",
	},
	navLinks: [
		{ text: "Home", href: "/" },
		{ text: "Services", href: "/services" },
		{ text: "About", href: "/about" },
		{ text: "Blog", href: "/blog" },
		{ text: "Resources", href: "/resources" },
		{ text: "FAQ", href: "/faq" },
		{ text: "Contact", href: "/contact" },
	],
	footerLinks: [
		{ text: "Privacy Policy", href: "/privacy-policy" },
		{ text: "Terms of Service", href: "/terms-of-service" },
		{ text: "Cookie Policy", href: "/cookie-policy" },
	],
	social: { facebook: "", twitter: "", instagram: "", linkedin: "" },
	cookieConsent: { cookiebotId: "" },
	tracking: {
		gtmId: "",
		ga4Id: "",
		fbPixelId: "",
		linkedinId: "",
		hubspotId: "",
		googleAdsId: "",
	},
	newsletter: {
		provider: "",
		hubspot: { portalId: "", formId: "" },
		mailchimp: { apiKey: "", listId: "" },
		activeCampaign: { apiUrl: "", token: "" },
	},
	features: {
		enableHeroSection: true,
		enableBlog: true,
		enableServices: true,
		enableContactForm: true,
		enableTestimonials: true,
		enablePricing: true,
		enableClientsSection: true,
		enableFeaturesSection: false,
		enableCtaSection: true,
		enableAboutSection: true,
		enableProblemPainSection: true,
		enableSolutionVisionSection: true,
		enableProcessSection: false,
		enableFaqSection: false,
		enableInspirationHeroSection: false,
		enableLandingPages: true,
	},
	enabledPages: [
		"/",
		"/services",
		"/about",
		"/blog",
		"/faq",
		"/resources",
		"/contact",
		"/terms-of-service",
	],
	contactForm: {
		provider: "smtp",
		fields: [
			{
				name: "name",
				type: "text",
				label: "Your name",
				placeholder: "Your name",
				required: true,
			},
			{
				name: "email",
				type: "email",
				label: "Your email",
				placeholder: "Your email",
				required: true,
			},
			{
				name: "phone",
				type: "tel",
				label: "Your phone (optional)",
				placeholder: "Your phone (optional)",
				required: false,
			},
			{
				name: "message",
				type: "textarea",
				label: "Message",
				placeholder: "How can we help you?",
				required: true,
			},
		],
		recaptchaSiteKey: "",
		honeypotFieldName: "honeypot",
	},
	contact: {
		email: "",
		phone: "",
		address: { line1: "", line2: "", city: "", zip: "", country: "" },
		hours: { monFri: "", sat: "", sun: "" },
	},
	sections: {
		hero: {
			badge: "",
			preTitle: "",
			words: [""],
			subtitle: "",
			image: { src: "", alt: "", fallback: "" },
			ctaPrimary: { text: "", href: "" },
			ctaSecondary: { text: "", href: "" },
			stats: [{ value: 0, suffix: "", label: "" }],
		},
		blog: { limit: 3 },
		pricing: {
			cards: [
				{
					title: "Basic",
					price: "$99/mo",
					features: ["Feature A", "Feature B", "Feature C"],
					cta: { text: "Choose Basic", href: "/#pricing" },
				},
				{
					title: "Pro",
					price: "$199/mo",
					features: ["Feature A", "Feature B", "Feature C", "Feature D"],
					cta: { text: "Choose Pro", href: "/#pricing" },
				},
				{
					title: "Enterprise",
					price: "$299/mo",
					features: ["All Pro features", "Feature E", "Feature F"],
					cta: { text: "Contact Sales", href: "/contact" },
				},
			],
		},
		// Add other section configs below (services, features, about, process, testimonials, cta, clients...)
	},
} as const;
